version: '2'
services:
  car-dealership:
    build: .
    environment:
      - CONFIG_FILE=./configs/config.json
    ports:
        - "5000:5000"
    volumes:
        - ./src:/app

  car-dealership-db:
    image: postgres
    restart: always
    environment: 
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: dev
    volumes:
      - ./extra/init-dbs.sh:/docker-entrypoint-initdb.d/init-dbs.sh
      - car-dealership-db-data:/var/lib/postgresql/data/
    ports:
      - "5438:5432"
    
volumes:
  car-dealership-db-data:
